
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(332, 390)
        MainWindow.setMinimumSize(QtCore.QSize(310, 390))
        MainWindow.setMaximumSize(QtCore.QSize(332, 476))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(10, 9, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.sonuc.setFont(font)
        self.sonuc.setFrameShape(QtWidgets.QFrame.Box)
        self.sonuc.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sonuc.setLineWidth(2)
        self.sonuc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sonuc.setObjectName("sonuc")
        self.yuzde = QtWidgets.QPushButton(self.centralwidget)
        self.yuzde.setGeometry(QtCore.QRect(4, 75, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.yuzde.setFont(font)
        self.yuzde.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.yuzde.setObjectName("yuzde")
        self.geri = QtWidgets.QPushButton(self.centralwidget)
        self.geri.setGeometry(QtCore.QRect(170, 75, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.geri.setFont(font)
        self.geri.setStyleSheet("background-color: rgb(241, 245, 245);\n"
"background-color: rgb(255, 255, 255);")
        self.geri.setObjectName("geri")
        self.silme = QtWidgets.QPushButton(self.centralwidget)
        self.silme.setGeometry(QtCore.QRect(85, 75, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.silme.setFont(font)
        self.silme.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.silme.setObjectName("silme")
        self.bolme = QtWidgets.QPushButton(self.centralwidget)
        self.bolme.setGeometry(QtCore.QRect(255, 75, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bolme.setFont(font)
        self.bolme.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bolme.setObjectName("bolme")
        self.sekiz = QtWidgets.QPushButton(self.centralwidget)
        self.sekiz.setGeometry(QtCore.QRect(85, 130, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sekiz.setFont(font)
        self.sekiz.setObjectName("sekiz")
        self.dokuz = QtWidgets.QPushButton(self.centralwidget)
        self.dokuz.setGeometry(QtCore.QRect(170, 130, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dokuz.setFont(font)
        self.dokuz.setObjectName("dokuz")
        self.carpma = QtWidgets.QPushButton(self.centralwidget)
        self.carpma.setGeometry(QtCore.QRect(255, 130, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.carpma.setFont(font)
        self.carpma.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.carpma.setObjectName("carpma")
        self.yedi = QtWidgets.QPushButton(self.centralwidget)
        self.yedi.setGeometry(QtCore.QRect(4, 130, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.yedi.setFont(font)
        self.yedi.setObjectName("yedi")
        self.bes = QtWidgets.QPushButton(self.centralwidget)
        self.bes.setGeometry(QtCore.QRect(85, 190, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bes.setFont(font)
        self.bes.setObjectName("bes")
        self.alti = QtWidgets.QPushButton(self.centralwidget)
        self.alti.setGeometry(QtCore.QRect(170, 190, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.alti.setFont(font)
        self.alti.setObjectName("alti")
        self.cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.cikarma.setGeometry(QtCore.QRect(255, 190, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cikarma.setFont(font)
        self.cikarma.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cikarma.setObjectName("cikarma")
        self.dort = QtWidgets.QPushButton(self.centralwidget)
        self.dort.setGeometry(QtCore.QRect(4, 190, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dort.setFont(font)
        self.dort.setObjectName("dort")
        self.iki = QtWidgets.QPushButton(self.centralwidget)
        self.iki.setGeometry(QtCore.QRect(85, 250, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.iki.setFont(font)
        self.iki.setObjectName("iki")
        self.uc = QtWidgets.QPushButton(self.centralwidget)
        self.uc.setGeometry(QtCore.QRect(170, 250, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.uc.setFont(font)
        self.uc.setObjectName("uc")
        self.toplama = QtWidgets.QPushButton(self.centralwidget)
        self.toplama.setGeometry(QtCore.QRect(255, 250, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.toplama.setFont(font)
        self.toplama.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toplama.setObjectName("toplama")
        self.bir = QtWidgets.QPushButton(self.centralwidget)
        self.bir.setGeometry(QtCore.QRect(4, 250, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bir.setFont(font)
        self.bir.setObjectName("bir")
        self.sifir = QtWidgets.QPushButton(self.centralwidget)
        self.sifir.setGeometry(QtCore.QRect(85, 310, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sifir.setFont(font)
        self.sifir.setObjectName("sifir")
        self.nokta = QtWidgets.QPushButton(self.centralwidget)
        self.nokta.setGeometry(QtCore.QRect(170, 310, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nokta.setFont(font)
        self.nokta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nokta.setObjectName("nokta")
        self.esittir = QtWidgets.QPushButton(self.centralwidget)
        self.esittir.setGeometry(QtCore.QRect(255, 310, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.esittir.setFont(font)
        self.esittir.setStyleSheet("color: rgb(255, 102, 2);\n"
"background-color: rgb(255, 255, 255);")
        self.esittir.setObjectName("esittir")
        self.isaret = QtWidgets.QPushButton(self.centralwidget)
        self.isaret.setGeometry(QtCore.QRect(4, 310, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.isaret.setFont(font)
        self.isaret.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.isaret.setObjectName("isaret")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hesap Makinesi"))
        self.sonuc.setText(_translate("MainWindow", "0"))
        self.yuzde.setText(_translate("MainWindow", "%"))
        self.geri.setText(_translate("MainWindow", "←"))
        self.silme.setText(_translate("MainWindow", "C"))
        self.bolme.setText(_translate("MainWindow", "/"))
        self.sekiz.setText(_translate("MainWindow", "8"))
        self.dokuz.setText(_translate("MainWindow", "9"))
        self.carpma.setText(_translate("MainWindow", "x"))
        self.yedi.setText(_translate("MainWindow", "7"))
        self.bes.setText(_translate("MainWindow", "5"))
        self.alti.setText(_translate("MainWindow", "6"))
        self.cikarma.setText(_translate("MainWindow", "-"))
        self.dort.setText(_translate("MainWindow", "4"))
        self.iki.setText(_translate("MainWindow", "2"))
        self.uc.setText(_translate("MainWindow", "3"))
        self.toplama.setText(_translate("MainWindow", "+"))
        self.bir.setText(_translate("MainWindow", "1"))
        self.sifir.setText(_translate("MainWindow", "0"))
        self.nokta.setText(_translate("MainWindow", "."))
        self.esittir.setText(_translate("MainWindow", "="))
        self.isaret.setText(_translate("MainWindow", "+/-"))
